### ISSUE TITLE
Day Required *

### ISSUE THREAD

**Issue by pixie79** [DigitalPatterns/formio-gds-template#11]
When you enabled the required flag on a Data Time box the little red required * does not appear .

**Comment by pixie79** [comment]
![Screenshot 2020-04-24 08 11 42](https://user-images.githubusercontent.com/534416/80184977-7be74780-8603-11ea-94c0-4afe85c1eebb.png)

**Comment by aminmc** [comment]
Is this day component or date time or both?

**Comment by aminmc** [comment]
Not able to reproduce this.
![Screenshot 2020-04-24 at 10 08 06](https://user-images.githubusercontent.com/290639/80195374-a5a86a80-8613-11ea-83ad-b9100e5bcb6f.png)
![Screenshot 2020-04-24 at 10 08 11](https://user-images.githubusercontent.com/290639/80195379-a6410100-8613-11ea-9e73-e23fda6c7119.png)

If you set required day, month and year then this works correctly.

**Comment by aminmc** [comment]
custom validation is also working.
